### ISSUE TITLE
Inquire the intron junctions of srav2

### ISSUE THREAD

**Issue by tewengtong** [ChristopherWilks/snaptron#18]
Hi, I'm recently using snaptron for my analysis. I saw there is a column called "DataSource:Type" （https://snaptron.cs.jhu.edu/srav2/snaptron?regions=ABCD3）, but I could find it in the srav2-junction files (https://snaptron.cs.jhu.edu/data/srav2/junctions.bgz). Would please tell me how can I extract all the intron junctions from sra2 dataset? Or how to get this column? Thank you very much!

**Comment by ChristopherWilks** [comment]
Hi @tewengtong,

The Snaptron (the service) adds the prefix of the compilation to each row on return (e.g. in this case "srav2").
That said, the backing data file, https://snaptron.cs.jhu.edu/data/srav2/junctions.bgz *only* contains junctions from the srav2 compilation, so any/all junctions there are what you're looking for if you're only interested in srav2 junctions.
