### ISSUE TITLE
Extra column during GET request by ids

### ISSUE THREAD

**Issue by PhaniGaddipati** [ChristopherWilks/snaptron#2]
**Example**
`curl "http://stingray.cs.jhu.edu:8443/snaptron?ids=snaptron:42691276"`

Expected Junction Output:
`SRA:I   42691276        chrY    2608008 2665015 57008   -       0       GC      AG      0       0       6320    1       1       1       1.000   1.000   1`

Actual Junction Output:
`SRA:I   42691276        42691275        chrY    2608008 2665015 57008   -       0       GC      AG      0       0       6320    1       1       1       1.000   1.000   1`

Extra column is always id-1

**Comment by ChristopherWilks** [comment]
should be fixed in latest commit to master d738064
