### ISSUE TITLE
Wrong header returned for GET while specifying fields

### ISSUE THREAD

**Issue by PhaniGaddipati** [ChristopherWilks/snaptron#3]
Request:
`http://stingray.cs.jhu.edu:8443/snaptron?regions=CD99&contains=1&fields=snaptron_id`

Response:
`snaptron_id`
`SRA:I	41342852`
`....`

The header is missing the DataSource:Type header column

**Comment by ChristopherWilks** [comment]
should be fixed now, header + prefix should be consistent now.

**Comment by PhaniGaddipati** [comment]
Looks like this bug popped up again
