### ISSUE TITLE
Wrong header returned for GET while specifying fields

### ISSUE THREAD

**Issue by PhaniGaddipati** [ChristopherWilks/snaptron#4]
Request:
http://stingray.cs.jhu.edu:8090/srav1/snaptron?regions=cd99&fields=snaptron_id

Response:
snaptron_id
SRA:I	41338338
SRA:I	41338408
....

The header is missing the DataSource:Type header column

**Comment by ChristopherWilks** [comment]
should be fixed, but I still need to come up with a test (I currently only test for the ids themselves, not the format)

**Comment by ChristopherWilks** [comment]
now have a test for this which catches this specific error
