### ISSUE TITLE
limit option on /annotations malforms output

### ISSUE THREAD

**Issue by PhaniGaddipati** [ChristopherWilks/snaptron#5]
Query:
`http://stingray.cs.jhu.edu:8090/srav1/annotations?regions=eml4`

Output:
`DataSource:Type	reference	annotation_source	feature_type	start	end	unused	strand	unused	attributes`

`Mixed:G	chr2	GC,ES,RG	transcript	42370378	42397371	.	-	.	transcript_id "ENST00000422013.2,ENST00000422013,NR_110584";cds_span "NA";exons "42370378-42370484,42374791-42374980,42377075-42377172,42397110-42397371";`

`...`

Query:
`http://stingray.cs.jhu.edu:8090/srav1/annotations?regions=eml4&limit=50`

Output:
`DataSource:Type	reference	annotation_source	feature_type	start	end	unused	strand	unused	attributes`

`Mixed:G	chr2	ES,GC	transcript	42396752	42558014	100024	+	.	transcript_id "ENST00000401738,ENST00000401738.3";cds_span "42396752-42557344";exons "42396601-42396776,42472645-42472827,42483641-42483770,42488261-42488434,42490318-42490446,42491846-42491871,42492059-42492091,42507990-42508113,42509963-42510112,42511774-42511843,42513409-42513519,42515367-42515462,42522265-42522399,42522521-42522656,42528381-42528532,42530244-42530369,42530455-42530586,42531624-42531691,42543102-42543190,42544567-42544664,42552607-42552694,42553294-42553392,42556026-42556156,42556874-42558014";`

`...`

`Mixed:G	exons "42370378-42370484,42374791-42374980,42377075-42377172,42397110-42397371"`

`...`

There are extra malformed lines when the &limit portion is included - the output stays the same (same # of bad lines) as long as limit > # models.

**Comment by ChristopherWilks** [comment]
looks like I left in a debug statement in the limit mini-script I had; this should be fixed now.

**Comment by ChristopherWilks** [comment]
reopening to be closed via commit
