### ISSUE TITLE
snaptron junctions filtered for GT/GC/AT donors and AG/AC acceptors?

### ISSUE THREAD

**Issue by isthisthat** [ChristopherWilks/snaptron#6]
Hello, I noticed that the junctions published here:
http://snaptron.cs.jhu.edu/data/srav1/
include only GT/GC/AT donors and AG/AC acceptors.
Is there an explicit filtering at some stage in the pipeline?
I'm interested in discovering variants creating aberrant splicing so was interested in the "non-canonical" junctions with respect to the reference. Do you have a list of those as well?
Thanks a lot.

**Comment by ChristopherWilks** [comment]
Hi Stathis,

Thanks for your interest in Snaptron.  

The Rail-RNA aligner that our group created and used to produce the junctions in Snaptron calls only novel splice sites (not guided by annotation).  As such it doesn't call any splice sites other than GT-AG, GC-AG, and AT-AC which is typical for modern spliced aligners making novel calls.  So we don't have any junctions with non-canonical splice sites beyond those.

Chris
